### ISSUE TITLE
Multiple searches

### ISSUE THREAD

**Issue by BardoBravo** [EloquentStudio/StreamTable.js#35]
Hi,
Is there a way to make multiple searches, like inserting the actor first name plus a year, and then have as response all movies with a given actor in a given year?

[]s
Cláudio Ramos

**Comment by jiren** [comment]
This functionality is not available as of now but you can override search function.

 https://github.com/jiren/StreamTable.js/blob/ebf42c2ea0e246e5b2ef82700e2d4b014979f9ed/stream_table.js#L249
