### ISSUE TITLE
Custom Filters data loading 

### ISSUE THREAD

**Issue by vaibhav8186** [EloquentStudio/StreamTable.js#38]
Once my data is loaded in the table, then I applied my custom filter which is one dropdown.
 If I select one value from a dropdown then request will go the backend and my query will return only 20 records out of 400 records. So stream-table fill these records and again request will go the backend, and again it will fetch the record and fill the table till it completes 400 records.
So If my query returns 20 records then stream-table has to fill only 20 records in a table. why it is going to the backend again?

**Comment by jiren** [comment]
I don't think so this is correct behavior. On select StreamTable will do only filtering it is not going to fetch data from the remote service. 
FYI - StreamTable will start fetching data when StreamTable object initializes and it requesting data in batches until empty response not receives.
